#!/bin/bash

# ==========================================
# Minimal IDC System (MIS) 自动部署脚本
# 适用系统: Ubuntu 20.04 / 22.04 LTS
# ==========================================

# 设置颜色
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

# 配置参数
DB_NAME="mis"
DB_USER="mis_user"
DB_PASS=$(openssl rand -base64 12 2>/dev/null || openssl rand -hex 12)
APP_KEY=$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p)
INSTALL_DIR="/var/www/mis"
GITHUB_REPO="https://github.com/bbb-lsy07/Minimal-IDC-System-MIS-.git"

# 默认管理员账号
ADMIN_EMAIL="admin@example.com"
ADMIN_PASS="admin123"

# 打印带颜色的消息
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# 检查是否为 Root 用户
if [ "$EUID" -ne 0 ]; then
    log_error "请使用 sudo 或 root 权限运行此脚本"
    exit 1
fi

log_info "开始部署 Minimal IDC System (MIS)..."

# ============================================
# 步骤 1: 更新系统并安装依赖
# ============================================
log_info "步骤 1/7: 更新系统并安装依赖..."

export DEBIAN_FRONTEND=noninteractive

apt-get update -y
apt-get install -y git curl unzip nginx mariadb-server mariadb-client

# 安装 PHP 及扩展
PHP_VER=$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;' 2>/dev/null || echo "8.1")
log_info "检测到 PHP 版本: $PHP_VER"

# 安装 PHP 扩展 (尝试多个版本)
for ver in "8.3" "8.2" "8.1" "8.0"; do
    if apt-cache show php${ver}-fpm >/dev/null 2>&1; then
        PHP_VER=$ver
        break
    fi
done

log_info "将安装 PHP $PHP_VER"

apt-get install -y php${PHP_VER}-fpm php${PHP_VER}-mysql php${PHP_VER}-curl php${PHP_VER}-json \
    php${PHP_VER}-mbstring php${PHP_VER}-xml php${PHP_VER}-ssh2 php${PHP_VER}-cli

# ============================================
# 步骤 2: 配置数据库
# ============================================
log_info "步骤 2/7: 配置数据库 (MariaDB)..."

systemctl start mariadb
systemctl enable mariadb

# 安全配置 (自动回复)
mysql -e "DROP DATABASE IF EXISTS test;" 2>/dev/null
mysql -e "DELETE FROM mysql.user WHERE User='';" 2>/dev/null
mysql -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1');" 2>/dev/null
mysql -e "FLUSH PRIVILEGES;" 2>/dev/null

# 创建数据库和用户
mysql -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
mysql -e "CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';"
mysql -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';"
mysql -e "FLUSH PRIVILEGES;"

log_info "数据库 ${DB_NAME} 和用户 ${DB_USER} 已创建"

# ============================================
# 步骤 3: 下载项目代码
# ============================================
log_info "步骤 3/7: 下载项目代码..."

if [ -d "$INSTALL_DIR" ]; then
    log_warn "目录 $INSTALL_DIR 已存在，正在备份..."
    mv "$INSTALL_DIR" "${INSTALL_DIR}_backup_$(date +%s)"
fi

git clone "$GITHUB_REPO" "$INSTALL_DIR"

if [ ! -d "$INSTALL_DIR" ]; then
    log_error "无法下载代码，请检查 GitHub 仓库地址"
    exit 1
fi

log_info "代码已下载到 $INSTALL_DIR"

# ============================================
# 步骤 4: 导入数据库结构 & 创建管理员
# ============================================
log_info "步骤 4/7: 导入数据库结构 & 创建管理员..."

# 导入 Schema
mysql "$DB_NAME" < "$INSTALL_DIR/sql/schema.sql"

# 生成管理员密码 Hash
ADMIN_HASH=$(php -r "echo password_hash('${ADMIN_PASS}', PASSWORD_DEFAULT);")

# 插入管理员账号
mysql "$DB_NAME" -e "INSERT INTO users (email, password_hash, balance, status, is_admin) VALUES ('${ADMIN_EMAIL}', '${ADMIN_HASH}', 9999, 'active', 1);"

log_info "默认管理员账号已创建: ${ADMIN_EMAIL} / ${ADMIN_PASS}"

# ============================================
# 步骤 5: 生成配置文件
# ============================================
log_info "步骤 5/7: 生成配置文件..."

# 获取服务器 IP
SERVER_IP=$(curl -s ifconfig.me 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}')
BASE_URL="http://${SERVER_IP}"

cat > "$INSTALL_DIR/config.local.php" <<EOF
<?php
/**
 * Local configuration - Auto-generated by install.sh
 * 这个文件会被 .gitignore 忽略，请妥善保管
 */
return [
    'db' => [
        'dsn' => 'mysql:host=127.0.0.1;dbname=${DB_NAME};charset=utf8mb4',
        'user' => '${DB_USER}',
        'pass' => '${DB_PASS}',
    ],
    'app_key' => '${APP_KEY}',
    'base_url' => '${BASE_URL}',
];
EOF

log_info "配置文件已生成: $INSTALL_DIR/config.local.php"

# ============================================
# 步骤 6: 配置 Nginx
# ============================================
log_info "步骤 6/7: 配置 Nginx..."

# 检测 PHP-FPM socket 路径
PHP_SOCKET=""
for sock in "/run/php/php${PHP_VER}-fpm.sock" "/var/run/php/php${PHP_VER}-fpm.sock"; do
    if [ -S "$sock" ]; then
        PHP_SOCKET=$sock
        break
    fi
done

# 如果找不到，使用默认路径
if [ -z "$PHP_SOCKET" ]; then
    PHP_SOCKET="/run/php/php${PHP_VER}-fpm.sock"
fi

cat > /etc/nginx/sites-available/mis <<EOF
server {
    listen 80;
    server_name _;
    root $INSTALL_DIR;
    index index.php index.html;

    # 访问日志
    access_log /var/log/nginx/mis_access.log;
    error_log /var/log/nginx/mis_error.log;

    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:${PHP_SOCKET};
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        include fastcgi_params;
    }

    # 禁止访问敏感文件
    location ~ /\.git {
        deny all;
        return 404;
    }

    location ~ ^/(sql|includes|templates|config\.local\.php|\.env) {
        deny all;
        return 404;
    }

    location ~ \.(sql|log|txt)$ {
        deny all;
        return 404;
    }
}
EOF

# 启用站点
ln -sf /etc/nginx/sites-available/mis /etc/nginx/sites-enabled/

# 移除默认站点（如果存在）
rm -f /etc/nginx/sites-enabled/default

# 测试并重载 Nginx
if nginx -t 2>/dev/null; then
    systemctl restart nginx
    log_info "Nginx 配置已应用"
else
    log_error "Nginx 配置测试失败"
    exit 1
fi

# ============================================
# 步骤 7: 设置权限与定时任务
# ============================================
log_info "步骤 7/7: 设置权限与定时任务..."

# 设置文件权限
chown -R www-data:www-data "$INSTALL_DIR"
chmod -R 755 "$INSTALL_DIR"
chmod 640 "$INSTALL_DIR/config.local.php"

# 添加 Cron 任务
CRON_JOB="* * * * * cd $INSTALL_DIR && /usr/bin/php cron.php all >> /var/log/mis_cron.log 2>&1"

# 检查是否已存在相同的 cron job
if crontab -l 2>/dev/null | grep -F "$INSTALL_DIR" > /dev/null; then
    log_warn "定时任务已存在，跳过添加"
else
    (crontab -l 2>/dev/null; echo "$CRON_JOB") | crontab -
    log_info "定时任务已添加"
fi

# ============================================
# 完成
# ============================================
echo ""
echo -e "${GREEN}==============================================${NC}"
echo -e "${GREEN}   安装完成! Minimal IDC System 已部署     ${NC}"
echo -e "${GREEN}==============================================${NC}"
echo ""
echo -e "访问地址:   ${GREEN}${BASE_URL}${NC}"
echo -e "管理入口:   ${GREEN}${BASE_URL}/admin.php${NC}"
echo ""
echo -e "管理员账号: ${GREEN}${ADMIN_EMAIL}${NC}"
echo -e "管理员密码: ${GREEN}${ADMIN_PASS}${NC}"
echo ""
echo -e "数据库名称: ${GREEN}${DB_NAME}${NC}"
echo -e "数据库用户: ${GREEN}${DB_USER}${NC}"
echo -e "数据库密码: ${GREEN}${DB_PASS}${NC}"
echo ""
echo -e "配置文件:   ${GREEN}$INSTALL_DIR/config.local.php${NC}"
echo -e "日志文件:   ${GREEN}/var/log/mis_cron.log${NC}"
echo ""
echo -e "${YELLOW}建议: 请尽快登录并修改默认管理员密码${NC}"
echo -e "${GREEN}==============================================${NC}"

